name: quizz4u
description: Quiz éducatif avec 5 catégories - Histoire du Mali, Culture générale, Sciences, Mathématiques et Afrique. Plus de 200 questions avec TTS, timer animé et classement local.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  flutter_tts: ^3.8.5
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: Signatra
      fonts:
        - asset: fonts/Signatra.ttf
    - family: Schuyler
      fonts:
        - asset: fonts/Schuyler.ttf
    - family: Sinatra
      fonts:
        - asset: fonts/Sinatra.ttf
    - family: robotomono
      fonts:
        - asset: fonts/robotomono-regular.ttf
        - asset: fonts/robotomono-bold.ttf
          weight: 700

  assets:
    - assets/animations/
    - assets/questions/mali_history_questions.json
    - assets/questions/general_culture_questions.json
    - assets/questions/science_questions.json
    - assets/questions/math_questions.json
    - assets/questions/africa_questions.json
