name: question_pour_toi
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  lucide_icons: ^0.257.0
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2  # Conserver uniquement cette ligne
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/hourglass.json
    - assets/animations/congrats.json
    # ajoute d'autres fichiers ici si besoin
    # - assets/sounds/correct.mp3
    # - assets/sounds/wrong.mp3

  fonts:
    - family: Signatra
      fonts:
        - asset: fonts/Signatra.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
