name: quizz4u
description: Quiz éducatif avec 5 catégories - Histoire du Mali, Culture générale, Sciences, Mathématiques et Afrique. Plus de 200 questions avec TTS, timer animé et classement local.

version: 2.0.5+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  flutter_tts: ^4.2.3
  url_launcher: ^6.2.4
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.1.13
  audioplayers: ^6.5.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.0
  google_fonts: ^6.1.0
  confetti: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  flame: ^1.30.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: Signatra
      fonts:
        - asset: fonts/Signatra.ttf
    - family: Schuyler
      fonts:
        - asset: fonts/Schuyler.ttf
    - family: Sinatra
      fonts:
        - asset: fonts/Sinatra.ttf
    - family: robotomono
      fonts:
        - asset: fonts/robotomono-regular.ttf
        - asset: fonts/robotomono-bold.ttf
          weight: 700

  assets:
    - assets/sounds/good.mp3
    - assets/sounds/bad.mp3
    - assets/sounds/background.mp3
    - assets/animations/
    - assets/questions/mali_history_questions.json
    - assets/questions/general_culture_questions.json
    - assets/questions/science_questions.json
    - assets/questions/math_questions.json
    - assets/questions/africa_questions.json
    - assets/questions/questions_extension_phase1.json
    - assets/questions/phase2_new_categories.json
    - assets/questions/phase3_advanced_questions.json
    - assets/questions/massive_extension_phase4.json
    - assets/questions/premium_questions_phase6.json
