/// Traducteur automatique en masse pour toutes les catégories
/// Utilise des règles linguistiques et des dictionnaires enrichis
///
/// Ce fichier contient TOUTES les traductions automatiques pour TOUTES les catégories
/// Généré automatiquement - Qualité acceptable pour un premier déploiement
class BulkAutoTranslator {
  /// Dictionnaires de termes par domaine
  static final Map<String, Map<String, Map<String, String>>> _domainTerms = {
    'common': {
      'en': {
        'de': 'of',
        'le': 'the',
        'la': 'the',
        'les': 'the',
        'un': 'a',
        'une': 'a',
        'du': 'of the',
        'de la': 'of the',
        "de l'": 'of the',
        'est': 'is',
        'sont': 'are',
        'et': 'and',
        'ou': 'or',
        'pour': 'for',
        'dans': 'in',
        'sur': 'on',
        'avec': 'with',
        'sans': 'without',
        'plus': 'more',
        'moins': 'less',
        'très': 'very',
        'aussi': 'also',
        'mais': 'but',
        'si': 'if',
        'car': 'because',
        'donc': 'therefore',
        'alors': 'then',
        'comme': 'like',
        'entre': 'between',
        'tous': 'all',
        'chaque': 'each',
        'plusieurs': 'several',
        'aucun': 'none',
        'millions': 'million',
        'milliards': 'billion',
        'années': 'years',
        'année': 'year',
        'km': 'km',
        'kilomètres': 'kilometers',
        'litres': 'liters',
        'litre': 'liter',
        // ENRICHISSEMENT MASSIF - VERBES FRÉQUENTS EN
        'appelle': 'call',
        'appelé': 'called',
        'appelée': 'called',
        'appeler': 'call',
        'nommé': 'named',
        'nommée': 'named',
        'nom': 'name',
        'trouve': 'find',
        'trouvé': 'found',
        'située': 'located',
        'situé': 'located',
        'devient': 'become',
        'devenu': 'became',
        'fait': 'make',
        'faire': 'make',
        'donne': 'give',
        'donné': 'given',
        'prend': 'take',
        'pris': 'taken',
        'dit': 'say',
        'dire': 'say',
        'va': 'go',
        'aller': 'go',
        'vient': 'come',
        'venir': 'come',
        'voit': 'see',
        'vu': 'seen',
        'sait': 'know',
        'savoir': 'know',
        'peut': 'can',
        'pouvoir': 'can',
        'doit': 'must',
        'devoir': 'must',
        'veut': 'want',
        'vouloir': 'want',
        // NOMS COMMUNS EN
        'chose': 'thing',
        'temps': 'time',
        'lieu': 'place',
        'personne': 'person',
        'gens': 'people',
        'homme': 'man',
        'femme': 'woman',
        'enfant': 'child',
        'famille': 'family',
        'monde': 'world',
        'vie': 'life',
        'mort': 'death',
        'jour': 'day',
        'nuit': 'night',
        'semaine': 'week',
        'mois': 'month',
        'heure': 'hour',
        'fois': 'time',
        'partie': 'part',
        'côté': 'side',
        'début': 'beginning',
        'fin': 'end',
        'milieu': 'middle',
        'centre': 'center',
        'bas': 'bottom',
        'gauche': 'left',
        'droite': 'right',
        'nord': 'north',
        'sud': 'south',
        'ouest': 'west',
        // ADJECTIFS EN
        'principal': 'main',
        'principale': 'main',
        'important': 'important',
        'célèbre': 'famous',
        'connu': 'known',
        'populaire': 'popular',
        'nombreux': 'numerous',
        'autre': 'other',
        'différent': 'different',
        'même': 'same',
        'seul': 'only',
        'unique': 'unique',
        'commun': 'common',
        'général': 'general',
        'spécial': 'special',
        'certain': 'certain',
        'possible': 'possible',
        'difficile': 'difficult',
        'facile': 'easy',
        'simple': 'simple',
        'complexe': 'complex',
        'fort': 'strong',
        'faible': 'weak',
        'long': 'long',
        'court': 'short',
        'large': 'wide',
        'étroit': 'narrow',
        'haut': 'high',
        'profond': 'deep',
        'léger': 'light',
        'lourd': 'heavy',
        'chaud': 'hot',
        'froid': 'cold',
        'sec': 'dry',
        'humide': 'humid',
        'propre': 'clean',
        'sale': 'dirty',
        'clair': 'clear',
        'sombre': 'dark',
        'jeune': 'young',
        'vieux': 'old',
        'ancien': 'ancient',
        'moderne': 'modern',
        'récent': 'recent',
      },
      'ar': {
        'de': 'من',
        'le': 'ال',
        'la': 'ال',
        'les': 'ال',
        'un': '',
        'une': '',
        'du': 'من ال',
        'de la': 'من ال',
        "de l'": 'من ال',
        'est': 'هو',
        'sont': 'هم',
        'et': 'و',
        'ou': 'أو',
        'pour': 'ل',
        'dans': 'في',
        'sur': 'على',
        'avec': 'مع',
        'sans': 'بدون',
        'plus': 'أكثر',
        'moins': 'أقل',
        'très': 'جدا',
        'aussi': 'أيضا',
        'mais': 'لكن',
        'si': 'إذا',
        'car': 'لأن',
        'donc': 'إذن',
        'alors': 'ثم',
        'comme': 'مثل',
        'entre': 'بين',
        'tous': 'جميع',
        'chaque': 'كل',
        'plusieurs': 'عدة',
        'aucun': 'لا أحد',
        // Mots fréquents supplémentaires
        'qui': 'الذي',
        'que': 'أن',
        'par': 'بواسطة',
        'son': 'له',
        'sa': 'لها',
        'ses': 'لهم',
        'ce': 'هذا',
        'cette': 'هذه',
        'ces': 'هؤلاء',
        'à': 'إلى',
        'au': 'إلى ال',
        'aux': 'إلى ال',
        'faire': 'فعل',
        'fait': 'فعل',
        'avoir': 'لديه',
        'être': 'يكون',
        'peut': 'يمكن',
        'doit': 'يجب',
        'veut': 'يريد',
        'dit': 'قال',
        'va': 'يذهب',
        'vient': 'يأتي',
        'premier': 'الأول',
        'première': 'الأولى',
        'deuxième': 'الثاني',
        'dernier': 'الأخير',
        'dernière': 'الأخيرة',
        'grand': 'كبير',
        'grande': 'كبيرة',
        'petit': 'صغير',
        'petite': 'صغيرة',
        'nouveau': 'جديد',
        'nouvelle': 'جديدة',
        'vieux': 'قديم',
        'vieille': 'قديمة',
        'bon': 'جيد',
        'bonne': 'جيدة',
        'mauvais': 'سيء',
        'mauvaise': 'سيئة',
        'bien': 'جيد',
        'mal': 'سيء',
        'beaucoup': 'كثيرا',
        'peu': 'قليلا',
        'trop': 'كثيرا جدا',
        'assez': 'كافٍ',
        'avant': 'قبل',
        'après': 'بعد',
        'pendant': 'خلال',
        'depuis': 'منذ',
        'maintenant': 'الآن',
        'aujourd': 'اليوم',
        "aujourd'hui": 'اليوم',
        'demain': 'غدا',
        'hier': 'أمس',
        'toujours': 'دائما',
        'jamais': 'أبدا',
        'souvent': 'غالبا',
        'parfois': 'أحيانا',
        'rarement': 'نادرا',
        // ENRICHISSEMENT MASSIF - VERBES FRÉQUENTS
        'appelle': 'يسمى',
        'appelé': 'يسمى',
        'appelée': 'تسمى',
        'appeler': 'يسمى',
        'nommé': 'مسمى',
        'nommée': 'مسماة',
        'nommer': 'يسمي',
        'connu': 'معروف',
        'connue': 'معروفة',
        'connaît': 'يعرف',
        'connaître': 'يعرف',
        'trouve': 'يجد',
        'trouvé': 'موجود',
        'trouvée': 'موجودة',
        'trouver': 'يجد',
        'situé': 'يقع',
        'située': 'تقع',
        'situer': 'يقع',
        'se trouve': 'يقع',
        'devient': 'يصبح',
        'devenu': 'أصبح',
        'devenue': 'أصبحت',
        'devenir': 'يصبح',
        'utilise': 'يستخدم',
        'utilisé': 'مستخدم',
        'utilisée': 'مستخدمة',
        'utiliser': 'يستخدم',
        'compose': 'يتكون',
        'composé': 'مكون',
        'composée': 'مكونة',
        'composer': 'يتكون',
        'contient': 'يحتوي',
        'contenu': 'محتوى',
        'contenir': 'يحتوي',
        'possède': 'يمتلك',
        'possédé': 'مملوك',
        'posséder': 'يمتلك',
        'produit': 'ينتج',
        'produire': 'ينتج',
        'crée': 'يخلق',
        'créé': 'مخلوق',
        'créée': 'مخلوقة',
        'créer': 'يخلق',
        'permet': 'يسمح',
        'permis': 'مسموح',
        'permettre': 'يسمح',
        'sert': 'يخدم',
        'servi': 'يخدم',
        'servir': 'يخدم',
        'représente': 'يمثل',
        'représenté': 'ممثل',
        'représentée': 'ممثلة',
        'représenter': 'يمثل',
        'signifie': 'يعني',
        'signifier': 'يعني',
        'désigne': 'يشير',
        'désigné': 'مشار',
        'désignée': 'مشارة',
        'désigner': 'يشير',
        'fonde': 'يؤسس',
        'fondé': 'مؤسس',
        'fondée': 'مؤسسة',
        'fonder': 'يؤسس',
        'découvre': 'يكتشف',
        'découvert': 'مكتشف',
        'découverte': 'مكتشفة',
        'découvrir': 'يكتشف',
        'invente': 'يخترع',
        'inventé': 'مخترع',
        'inventée': 'مخترعة',
        'inventer': 'يخترع',
        'écrit': 'يكتب',
        'écrire': 'يكتب',
        'parle': 'يتحدث',
        'parlé': 'متحدث',
        'parler': 'يتحدث',
        'voit': 'يرى',
        'vu': 'مرئي',
        'vue': 'مرئية',
        'voir': 'يرى',
        'entend': 'يسمع',
        'entendu': 'مسموع',
        'entendre': 'يسمع',
        'pense': 'يفكر',
        'pensé': 'مفكر',
        'penser': 'يفكر',
        'croit': 'يعتقد',
        'cru': 'معتقد',
        'croire': 'يعتقد',
        'sait': 'يعرف',
        'su': 'معروف',
        'savoir': 'يعرف',
        'donne': 'يعطي',
        'donné': 'معطى',
        'donnée': 'معطاة',
        'donner': 'يعطي',
        'prend': 'يأخذ',
        'pris': 'مأخوذ',
        'prise': 'مأخوذة',
        'prendre': 'يأخذ',
        'met': 'يضع',
        'mis': 'موضوع',
        'mise': 'موضوعة',
        'mettre': 'يضع',
        'reçoit': 'يتلقى',
        'reçu': 'متلقى',
        'reçue': 'متلقاة',
        'recevoir': 'يتلقى',
        'envoie': 'يرسل',
        'envoyé': 'مرسل',
        'envoyée': 'مرسلة',
        'envoyer': 'يرسل',
        // NOMS COMMUNS FRÉQUENTS
        'nom': 'اسم',
        'chose': 'شيء',
        'temps': 'وقت',
        'lieu': 'مكان',
        'endroit': 'مكان',
        'personne': 'شخص',
        'gens': 'ناس',
        'homme': 'رجل',
        'femme': 'امرأة',
        'enfant': 'طفل',
        'famille': 'عائلة',
        'monde': 'عالم',
        'vie': 'حياة',
        'mort': 'موت',
        'jour': 'يوم',
        'nuit': 'ليلة',
        'matin': 'صباح',
        'soir': 'مساء',
        'semaine': 'أسبوع',
        'mois': 'شهر',
        'heure': 'ساعة',
        'minute': 'دقيقة',
        'seconde': 'ثانية',
        'moment': 'لحظة',
        'fois': 'مرة',
        'partie': 'جزء',
        'côté': 'جانب',
        'bout': 'طرف',
        'début': 'بداية',
        'fin': 'نهاية',
        'milieu': 'وسط',
        'centre': 'مركز',
        'bord': 'حافة',
        'surface': 'سطح',
        'fond': 'قاع',
        'bas': 'أسفل',
        'gauche': 'يسار',
        'droite': 'يمين',
        'nord': 'شمال',
        'sud': 'جنوب',
        'ouest': 'غرب',
        // ADJECTIFS FRÉQUENTS
        'principal': 'رئيسي',
        'principale': 'رئيسية',
        'important': 'مهم',
        'importante': 'مهمة',
        'célèbre': 'مشهور',
        'populaire': 'شعبي',
        'nombreux': 'عديد',
        'nombreuse': 'عديدة',
        'autre': 'آخر',
        'différent': 'مختلف',
        'différente': 'مختلفة',
        'même': 'نفس',
        'seul': 'وحيد',
        'seule': 'وحيدة',
        'unique': 'فريد',
        'commun': 'مشترك',
        'commune': 'مشتركة',
        'général': 'عام',
        'générale': 'عامة',
        'spécial': 'خاص',
        'spéciale': 'خاصة',
        'particulier': 'خاص',
        'particulière': 'خاصة',
        'certain': 'مؤكد',
        'certaine': 'مؤكدة',
        'possible': 'ممكن',
        'impossible': 'مستحيل',
        'difficile': 'صعب',
        'facile': 'سهل',
        'simple': 'بسيط',
        'complexe': 'معقد',
        'fort': 'قوي',
        'forte': 'قوية',
        'faible': 'ضعيف',
        'long': 'طويل',
        'longue': 'طويلة',
        'court': 'قصير',
        'courte': 'قصيرة',
        'large': 'واسع',
        'étroit': 'ضيق',
        'haut': 'عالي',
        'haute': 'عالية',
        'profond': 'عميق',
        'profonde': 'عميقة',
        'léger': 'خفيف',
        'légère': 'خفيفة',
        'lourd': 'ثقيل',
        'lourde': 'ثقيلة',
        'chaud': 'حار',
        'chaude': 'حارة',
        'froid': 'بارد',
        'froide': 'باردة',
        'sec': 'جاف',
        'sèche': 'جافة',
        'humide': 'رطب',
        'mouillé': 'مبلل',
        'mouillée': 'مبللة',
        'propre': 'نظيف',
        'sale': 'متسخ',
        'pur': 'نقي',
        'pure': 'نقية',
        'clair': 'واضح',
        'claire': 'واضحة',
        'sombre': 'مظلم',
        'lumineux': 'مضيء',
        'lumineuse': 'مضيئة',
        'brillant': 'لامع',
        'brillante': 'لامعة',
        'doux': 'ناعم',
        'douce': 'ناعمة',
        'dur': 'صلب',
        'dure': 'صلبة',
        'mou': 'طري',
        'molle': 'طرية',
        'solide': 'صلب',
        'liquide': 'سائل',
        'gazeux': 'غازي',
        'gazeuse': 'غازية',
        'vivant': 'حي',
        'vivante': 'حية',
        'jeune': 'شاب',
        'récent': 'حديث',
        'récente': 'حديثة',
        'actuel': 'حالي',
        'actuelle': 'حالية',
        'futur': 'مستقبلي',
        'future': 'مستقبلية',
        'passé': 'ماضي',
        'présent': 'حاضر',
        'présente': 'حاضرة',
        // PRONOMS ET DÉTERMINANTS
        'je': 'أنا',
        'tu': 'أنت',
        'il': 'هو',
        'elle': 'هي',
        'nous': 'نحن',
        'vous': 'أنتم',
        'ils': 'هم',
        'elles': 'هن',
        'mon': 'لي',
        'ma': 'لي',
        'mes': 'لي',
        'ton': 'لك',
        'ta': 'لك',
        'tes': 'لك',
        'notre': 'لنا',
        'nos': 'لنا',
        'votre': 'لكم',
        'vos': 'لكم',
        'leur': 'لهم',
        'leurs': 'لهم',
        'celui': 'الذي',
        'celle': 'التي',
        'ceux': 'الذين',
        'celles': 'اللاتي',
        'ceci': 'هذا',
        'cela': 'ذلك',
        'ça': 'ذلك',
        'quoi': 'ماذا',
        'lequel': 'أيهما',
        'laquelle': 'أيتهما',
        'lesquels': 'أيهم',
        'lesquelles': 'أيهن',
        // NOMBRES
        'zéro': 'صفر',
        'deux': 'اثنان',
        'trois': 'ثلاثة',
        'quatre': 'أربعة',
        'cinq': 'خمسة',
        'six': 'ستة',
        'sept': 'سبعة',
        'huit': 'ثمانية',
        'neuf': 'تسعة',
        'dix': 'عشرة',
        'onze': 'أحد عشر',
        'douze': 'اثنا عشر',
        'treize': 'ثلاثة عشر',
        'quatorze': 'أربعة عشر',
        'quinze': 'خمسة عشر',
        'seize': 'ستة عشر',
        'vingt': 'عشرون',
        'trente': 'ثلاثون',
        'quarante': 'أربعون',
        'cinquante': 'خمسون',
        'soixante': 'ستون',
        'cent': 'مئة',
        'mille': 'ألف',
        'million': 'مليون',
        'milliard': 'مليار',
        // EXPRESSIONS ET LOCUTIONS
        'à partir de': 'من',
        'grâce à': 'بفضل',
        'à cause de': 'بسبب',
        'en raison de': 'بسبب',
        'afin de': 'من أجل',
        'par rapport à': 'بالنسبة ل',
        'au sujet de': 'حول',
        'quant à': 'أما',
        'selon': 'وفقا ل',
        'malgré': 'رغم',
        'tandis que': 'بينما',
        'alors que': 'في حين',
        'bien que': 'على الرغم من',
        'parce que': 'لأن',
        "c'est": 'إنه',
        "s'il": 'إذا',
        "d'où": 'من أين',
        "d'ici": 'من هنا',
        "jusqu'à": 'حتى',
        "jusqu'au": 'حتى',
        'au-dessus': 'فوق',
        'au-dessous': 'تحت',
        'autour': 'حول',
        'près': 'قريب',
        'loin': 'بعيد',
        'ici': 'هنا',
        'là': 'هناك',
        'là-bas': 'هناك',
        'partout': 'في كل مكان',
        'nulle part': 'لا مكان',
        'quelque part': 'في مكان ما',
        'ailleurs': 'في مكان آخر',
      },
      'zh': {
        'de': '的',
        'le': '',
        'la': '',
        'les': '',
        'un': '一个',
        'une': '一个',
        'du': '的',
        'de la': '的',
        "de l'": '的',
        'est': '是',
        'sont': '是',
        'et': '和',
        'ou': '或',
        'pour': '为',
        'dans': '在',
        'sur': '上',
        'avec': '与',
        'sans': '没有',
        'plus': '更',
        'moins': '较少',
        'très': '非常',
        'aussi': '也',
        'mais': '但',
        'si': '如果',
        'car': '因为',
        'donc': '所以',
        'alors': '那么',
        'comme': '像',
        'entre': '之间',
        'tous': '所有',
        'chaque': '每',
        'plusieurs': '几个',
        'aucun': '没有',
        // ENRICHISSEMENT ZH
        'appelle': '称',
        'appelé': '称为',
        'nom': '名称',
        'chose': '事物',
        'temps': '时间',
        'lieu': '地方',
        'personne': '人',
        'gens': '人们',
        'homme': '男人',
        'femme': '女人',
        'enfant': '孩子',
        'famille': '家庭',
        'monde': '世界',
        'vie': '生活',
        'mort': '死亡',
        'jour': '天',
        'nuit': '夜',
        'semaine': '周',
        'mois': '月',
        'heure': '小时',
        'fois': '次',
        'partie': '部分',
        'début': '开始',
        'fin': '结束',
        'milieu': '中间',
        'centre': '中心',
        'nord': '北',
        'sud': '南',
        'ouest': '西',
        'principal': '主要',
        'important': '重要',
        'célèbre': '著名',
        'connu': '已知',
        'populaire': '流行',
        'nombreux': '许多',
        'autre': '其他',
        'différent': '不同',
        'même': '相同',
        'seul': '唯一',
        'unique': '独特',
        'commun': '共同',
        'général': '一般',
        'spécial': '特别',
        'possible': '可能',
        'difficile': '困难',
        'facile': '容易',
        'simple': '简单',
        'complexe': '复杂',
        'fort': '强',
        'faible': '弱',
        'long': '长',
        'court': '短',
        'large': '宽',
        'haut': '高',
        'profond': '深',
        'léger': '轻',
        'lourd': '重',
        'chaud': '热',
        'froid': '冷',
        'jeune': '年轻',
        'vieux': '老',
        'ancien': '古',
        'moderne': '现代',
      },
      'hi': {
        'de': 'का',
        'le': '',
        'la': '',
        'les': '',
        'un': 'एक',
        'une': 'एक',
        'du': 'का',
        'de la': 'की',
        "de l'": 'का',
        'est': 'है',
        'sont': 'हैं',
        'et': 'और',
        'ou': 'या',
        'pour': 'के लिए',
        'dans': 'में',
        'sur': 'पर',
        'avec': 'के साथ',
        'sans': 'बिना',
        'plus': 'अधिक',
        'moins': 'कम',
        'très': 'बहुत',
        'aussi': 'भी',
        'mais': 'लेकिन',
        'si': 'अगर',
        'car': 'क्योंकि',
        'donc': 'इसलिए',
        'alors': 'तो',
        'comme': 'जैसे',
        'entre': 'के बीच',
        'tous': 'सभी',
        'chaque': 'प्रत्येक',
        'plusieurs': 'कई',
        'aucun': 'कोई नहीं',
        'millions': 'मिलियन',
        'milliards': 'बिलियन',
        'années': 'वर्ष',
        'année': 'वर्ष',
        'km': 'किमी',
        'kilomètres': 'किलोमीटर',
        'litres': 'लीटर',
        'litre': 'लीटर',
        // ENRICHISSEMENT HI
        'appelle': 'कहा जाता है',
        'appelé': 'कहा जाता है',
        'nom': 'नाम',
        'chose': 'चीज़',
        'temps': 'समय',
        'lieu': 'स्थान',
        'personne': 'व्यक्ति',
        'gens': 'लोग',
        'homme': 'आदमी',
        'femme': 'महिला',
        'enfant': 'बच्चा',
        'famille': 'परिवार',
        'monde': 'दुनिया',
        'vie': 'जीवन',
        'mort': 'मृत्यु',
        'jour': 'दिन',
        'nuit': 'रात',
        'semaine': 'सप्ताह',
        'mois': 'महीना',
        'heure': 'घंटा',
        'fois': 'बार',
        'partie': 'भाग',
        'début': 'शुरुआत',
        'fin': 'अंत',
        'milieu': 'मध्य',
        'centre': 'केंद्र',
        'nord': 'उत्तर',
        'sud': 'दक्षिण',
        'ouest': 'पश्चिम',
        'principal': 'मुख्य',
        'important': 'महत्वपूर्ण',
        'célèbre': 'प्रसिद्ध',
        'connu': 'ज्ञात',
        'populaire': 'लोकप्रिय',
        'nombreux': 'कई',
        'autre': 'अन्य',
        'différent': 'भिन्न',
        'même': 'समान',
        'seul': 'केवल',
        'unique': 'अद्वितीय',
        'commun': 'सामान्य',
        'général': 'सामान्य',
        'spécial': 'विशेष',
        'possible': 'संभव',
        'difficile': 'कठिन',
        'facile': 'आसान',
        'simple': 'सरल',
        'complexe': 'जटिल',
        'fort': 'मजबूत',
        'faible': 'कमजोर',
        'long': 'लंबा',
        'court': 'छोटा',
        'large': 'चौड़ा',
        'haut': 'ऊंचा',
        'profond': 'गहरा',
        'léger': 'हल्का',
        'lourd': 'भारी',
        'chaud': 'गर्म',
        'froid': 'ठंडा',
        'jeune': 'युवा',
        'vieux': 'बूढ़ा',
        'ancien': 'प्राचीन',
        'moderne': 'आधुनिक',
      },
      'es': {
        'de': 'de',
        'le': 'el',
        'la': 'la',
        'les': 'los',
        'un': 'un',
        'une': 'una',
        'du': 'del',
        'de la': 'de la',
        "de l'": 'del',
        'est': 'es',
        'sont': 'son',
        'et': 'y',
        'ou': 'o',
        'pour': 'para',
        'dans': 'en',
        'sur': 'sobre',
        'avec': 'con',
        'sans': 'sin',
        'plus': 'más',
        'moins': 'menos',
        'très': 'muy',
        'aussi': 'también',
        'mais': 'pero',
        'si': 'si',
        'car': 'porque',
        'donc': 'entonces',
        'alors': 'entonces',
        'comme': 'como',
        'entre': 'entre',
        'tous': 'todos',
        'chaque': 'cada',
        'plusieurs': 'varios',
        'aucun': 'ninguno',
        // ENRICHISSEMENT ES
        'appelle': 'llama',
        'appelé': 'llamado',
        'nom': 'nombre',
        'chose': 'cosa',
        'temps': 'tiempo',
        'lieu': 'lugar',
        'personne': 'persona',
        'gens': 'gente',
        'homme': 'hombre',
        'femme': 'mujer',
        'enfant': 'niño',
        'famille': 'familia',
        'monde': 'mundo',
        'vie': 'vida',
        'mort': 'muerte',
        'jour': 'día',
        'nuit': 'noche',
        'semaine': 'semana',
        'mois': 'mes',
        'heure': 'hora',
        'fois': 'vez',
        'partie': 'parte',
        'début': 'comienzo',
        'fin': 'fin',
        'milieu': 'medio',
        'centre': 'centro',
        'nord': 'norte',
        'sud': 'sur',
        'ouest': 'oeste',
        'principal': 'principal',
        'important': 'importante',
        'célèbre': 'famoso',
        'connu': 'conocido',
        'populaire': 'popular',
        'nombreux': 'numerosos',
        'autre': 'otro',
        'différent': 'diferente',
        'même': 'mismo',
        'seul': 'solo',
        'unique': 'único',
        'commun': 'común',
        'général': 'general',
        'spécial': 'especial',
        'possible': 'posible',
        'difficile': 'difícil',
        'facile': 'fácil',
        'simple': 'simple',
        'complexe': 'complejo',
        'fort': 'fuerte',
        'faible': 'débil',
        'long': 'largo',
        'court': 'corto',
        'large': 'ancho',
        'haut': 'alto',
        'profond': 'profundo',
        'léger': 'ligero',
        'lourd': 'pesado',
        'chaud': 'caliente',
        'froid': 'frío',
        'jeune': 'joven',
        'vieux': 'viejo',
        'ancien': 'antiguo',
        'moderne': 'moderno',
      },
    },
    'geography': {
      'en': {
        'pays': 'country',
        'capitale': 'capital',
        'ville': 'city',
        'région': 'region',
        'fleuve': 'river',
        'mont': 'mount',
        'montagne': 'mountain',
        'océan': 'ocean',
        'mer': 'sea',
        'lac': 'lake',
        'désert': 'desert',
        'forêt': 'forest',
        'continent': 'continent',
        'île': 'island',
        'côte': 'coast',
      },
      'ar': {
        'pays': 'بلد',
        'capitale': 'عاصمة',
        'ville': 'مدينة',
        'région': 'منطقة',
        'fleuve': 'نهر',
        'montagne': 'جبل',
        'mont': 'جبل',
        'océan': 'محيط',
        'mer': 'بحر',
        'lac': 'بحيرة',
        'désert': 'صحراء',
        'forêt': 'غابة',
        'continent': 'قارة',
        'île': 'جزيرة',
        'côte': 'ساحل',
        // ENRICHISSEMENT GÉOGRAPHIE AR
        'vallée': 'وادي',
        'plaine': 'سهل',
        'plateau': 'هضبة',
        'volcan': 'بركان',
        'cascade': 'شلال',
        'rivière': 'نهر',
        'affluent': 'رافد',
        'delta': 'دلتا',
        'golfe': 'خليج',
        'baie': 'خليج',
        'péninsule': 'شبه جزيرة',
        'archipel': 'أرخبيل',
        'atoll': 'جزيرة مرجانية',
        'récif': 'شعاب مرجانية',
        'plage': 'شاطئ',
        'falaise': 'جرف',
        'colline': 'تل',
        'sommet': 'قمة',
        'pic': 'قمة',
        'chaîne': 'سلسلة',
        'massif': 'كتلة',
        'gorge': 'مضيق',
        'canyon': 'وادي ضيق',
        'grotte': 'كهف',
        'caverne': 'كهف',
        'tunnel': 'نفق',
        'pont': 'جسر',
        'canal': 'قناة',
        'port': 'ميناء',
        'frontière': 'حدود',
        'territoire': 'إقليم',
        'province': 'مقاطعة',
        'état': 'ولاية',
        'département': 'محافظة',
        'district': 'مقاطعة',
        'commune': 'بلدية',
        'village': 'قرية',
        'hameau': 'قرية صغيرة',
        'métropole': 'عاصمة كبرى',
        'agglomération': 'تجمع حضري',
        'banlieue': 'ضاحية',
        'quartier': 'حي',
        'rue': 'شارع',
        'avenue': 'جادة',
        'boulevard': 'شارع واسع',
        'place': 'ساحة',
        'parc': 'حديقة',
        'jardin': 'حديقة',
        'monument': 'نصب تذكاري',
        'édifice': 'مبنى',
        'bâtiment': 'مبنى',
        'tour': 'برج',
        'château': 'قلعة',
        'palais': 'قصر',
        'temple': 'معبد',
        'mosquée': 'مسجد',
        'église': 'كنيسة',
        'cathédrale': 'كاتدرائية',
        'synagogue': 'كنيس',
        'musée': 'متحف',
        'bibliothèque': 'مكتبة',
        'université': 'جامعة',
        'école': 'مدرسة',
        'hôpital': 'مستشفى',
        'marché': 'سوق',
        'gare': 'محطة',
        'aéroport': 'مطار',
        'stade': 'ملعب',
        'théâtre': 'مسرح',
        'cinéma': 'سينما',
        'hôtel': 'فندق',
        'restaurant': 'مطعم',
      },
      'zh': {
        'pays': '国家',
        'capitale': '首都',
        'ville': '城市',
        'région': '地区',
        'fleuve': '河流',
        'montagne': '山',
        'océan': '海洋',
        'mer': '海',
        'lac': '湖',
        'désert': '沙漠',
        'forêt': '森林',
        'continent': '大陆',
        'île': '岛',
        'côte': '海岸',
      },
      'hi': {
        'pays': 'देश',
        'capitale': 'राजधानी',
        'ville': 'शहर',
        'région': 'क्षेत्र',
        'fleuve': 'नदी',
        'montagne': 'पहाड़',
        'océan': 'महासागर',
        'mer': 'समुद्र',
        'lac': 'झील',
        'désert': 'रेगिस्तान',
        'forêt': 'जंगल',
        'continent': 'महाद्वीप',
        'île': 'द्वीप',
        'côte': 'तट',
      },
      'es': {
        'pays': 'país',
        'capitale': 'capital',
        'ville': 'ciudad',
        'région': 'región',
        'fleuve': 'río',
        'montagne': 'montaña',
        'océan': 'océano',
        'mer': 'mar',
        'lac': 'lago',
        'désert': 'desierto',
        'forêt': 'bosque',
        'continent': 'continente',
        'île': 'isla',
        'côte': 'costa',
      },
    },
    'history': {
      'en': {
        'empire': 'empire',
        'empereur': 'emperor',
        'roi': 'king',
        'reine': 'queen',
        'président': 'president',
        'premier': 'first',
        'guerre': 'war',
        'bataille': 'battle',
        'victoire': 'victory',
        'défaite': 'defeat',
        'indépendance': 'independence',
        'indépendant': 'independent',
        'colonie': 'colony',
        'dynastie': 'dynasty',
        'siècle': 'century',
        'année': 'year',
        'règne': 'reign',
        'révolution': 'revolution',
        'pèlerinage': 'pilgrimage',
        'célèbre': 'famous',
        'apogée': 'peak',
        'fondé': 'founded',
        'fondation': 'foundation',
        'capitale': 'capital',
        'ville': 'city',
        'griot': 'griot',
        'malien': 'Malian',
        'malienne': 'Malian',
        'surnommée': 'nicknamed',
        'surnommé': 'nicknamed',
        'perle': 'pearl',
        'désert': 'desert',
        'son': 'his',
        'sa': 'his',
        'ses': 'his',
      },
      'ar': {
        'empire': 'إمبراطورية',
        'empereur': 'إمبراطور',
        'roi': 'ملك',
        'reine': 'ملكة',
        'président': 'رئيس',
        'premier': 'الأول',
        'guerre': 'حرب',
        'bataille': 'معركة',
        'victoire': 'نصر',
        'défaite': 'هزيمة',
        'indépendance': 'استقلال',
        'indépendant': 'مستقل',
        'colonie': 'مستعمرة',
        'dynastie': 'سلالة',
        'siècle': 'قرن',
        'année': 'عام',
        'règne': 'حكم',
        'révolution': 'ثورة',
        'pèlerinage': 'حج',
        'célèbre': 'مشهور',
        'apogée': 'ذروة',
        'fondé': 'أسس',
        'fondée': 'أسست',
        'fondation': 'تأسيس',
        'griot': 'حكواتي',
        'malien': 'مالي',
        'malienne': 'مالية',
        'surnommée': 'الملقبة',
        'surnommé': 'الملقب',
        'perle': 'لؤلؤة',
        // ENRICHISSEMENT HISTOIRE AR
        'prince': 'أمير',
        'princesse': 'أميرة',
        'sultan': 'سلطان',
        'calife': 'خليفة',
        'émir': 'أمير',
        'ministre': 'وزير',
        'général': 'جنرال',
        'commandant': 'قائد',
        'chef': 'زعيم',
        'leader': 'قائد',
        'gouverneur': 'حاكم',
        'vice-roi': 'نائب الملك',
        'régent': 'وصي',
        'héritier': 'وريث',
        'successeur': 'خليفة',
        'prédécesseur': 'سلف',
        'ancêtre': 'سلف',
        'descendant': 'نسل',
        'nation': 'أمة',
        'peuple': 'شعب',
        'population': 'سكان',
        'citoyen': 'مواطن',
        'esclave': 'عبد',
        'serf': 'قن',
        'noble': 'نبيل',
        'noblesse': 'نبلاء',
        'aristocratie': 'ارستقراطية',
        'bourgeoisie': 'برجوازية',
        'classe': 'طبقة',
        'caste': 'طائفة',
        'tribu': 'قبيلة',
        'clan': 'عشيرة',
        'lignée': 'سلالة',
        'traité': 'معاهدة',
        'accord': 'اتفاق',
        'pacte': 'ميثاق',
        'alliance': 'تحالف',
        'conflit': 'صراع',
        'conquête': 'فتح',
        'invasion': 'غزو',
        'siège': 'حصار',
        'attaque': 'هجوم',
        'défense': 'دفاع',
        'armée': 'جيش',
        'troupe': 'قوة',
        'soldat': 'جندي',
        'guerrier': 'محارب',
        'combattant': 'مقاتل',
        'armement': 'تسليح',
        'arme': 'سلاح',
        'épée': 'سيف',
        'lance': 'رمح',
        'flèche': 'سهم',
        'arc': 'قوس',
        'bouclier': 'درع',
        'canon': 'مدفع',
        'fusil': 'بندقية',
        'révolte': 'ثورة',
        'rébellion': 'تمرد',
        'coup': 'انقلاب',
        'putsch': 'انقلاب',
        'assassinat': 'اغتيال',
        'complot': 'مؤامرة',
        'trahison': 'خيانة',
        'exil': 'نفي',
        'bannissement': 'طرد',
        'abdication': 'تنازل',
        'couronnement': 'تتويج',
        'sacre': 'تقديس',
        'cérémonie': 'حفل',
        'rituel': 'طقس',
        'tradition': 'تقليد',
        'coutume': 'عادة',
        'loi': 'قانون',
        'décret': 'مرسوم',
        'édit': 'أمر',
        'constitution': 'دستور',
        'charte': 'ميثاق',
        'code': 'قانون',
        'droit': 'حق',
        'justice': 'عدالة',
        'tribunal': 'محكمة',
        'juge': 'قاضي',
        'procès': 'محاكمة',
        'verdict': 'حكم',
        'sentence': 'عقوبة',
        'peine': 'عقوبة',
        'prison': 'سجن',
        'exécution': 'إعدام',
        'réforme': 'إصلاح',
        'changement': 'تغيير',
        'transformation': 'تحول',
        'modernisation': 'تحديث',
        'progrès': 'تقدم',
        'développement': 'تنمية',
        'déclin': 'انحدار',
        'chute': 'سقوط',
        'effondrement': 'انهيار',
        'crise': 'أزمة',
        'catastrophe': 'كارثة',
        'épidémie': 'وباء',
        'famine': 'مجاعة',
        'sécheresse': 'جفاف',
        'inondation': 'فيضان',
        'tremblement': 'زلزال',
        'séisme': 'زلزال',
      },
      'zh': {
        'empire': '帝国',
        'empereur': '皇帝',
        'roi': '国王',
        'reine': '女王',
        'président': '总统',
        'guerre': '战争',
        'bataille': '战役',
        'victoire': '胜利',
        'indépendance': '独立',
        'dynastie': '朝代',
        'siècle': '世纪',
        'année': '年',
        'révolution': '革命',
      },
      'hi': {
        'empire': 'साम्राज्य',
        'empereur': 'सम्राट',
        'roi': 'राजा',
        'reine': 'रानी',
        'président': 'राष्ट्रपति',
        'premier': 'पहला',
        'guerre': 'युद्ध',
        'bataille': 'लड़ाई',
        'victoire': 'विजय',
        'indépendance': 'स्वतंत्रता',
        'indépendant': 'स्वतंत्र',
        'dynastie': 'राजवंश',
        'siècle': 'सदी',
        'année': 'वर्ष',
        'révolution': 'क्रांति',
        'pèlerinage': 'तीर्थयात्रा',
        'célèbre': 'प्रसिद्ध',
        'apogée': 'चरम',
        'fondé': 'स्थापित',
        'fondation': 'स्थापना',
        'capitale': 'राजधानी',
        'ville': 'शहर',
        'griot': 'गीतकार',
        'malien': 'मालियन',
        'malienne': 'मालियन',
        'surnommée': 'उपनाम',
        'surnommé': 'उपनाम',
        'perle': 'मोती',
        'désert': 'रेगिस्तान',
        'son': 'उसका',
        'sa': 'उसकी',
        'ses': 'उसके',
      },
      'es': {
        'empire': 'imperio',
        'empereur': 'emperador',
        'roi': 'rey',
        'reine': 'reina',
        'président': 'presidente',
        'guerre': 'guerra',
        'bataille': 'batalla',
        'victoire': 'victoria',
        'indépendance': 'independencia',
        'dynastie': 'dinastía',
        'siècle': 'siglo',
        'année': 'año',
        'révolution': 'revolución',
      },
    },
    'science': {
      'en': {
        'planète': 'planet',
        'étoile': 'star',
        'soleil': 'sun',
        'lune': 'moon',
        'terre': 'earth',
        'eau': 'water',
        'air': 'air',
        'feu': 'fire',
        'lumière': 'light',
        'chaleur': 'heat',
        'énergie': 'energy',
        'atome': 'atom',
        'molécule': 'molecule',
        'cellule': 'cell',
        'unité': 'unit',
        'mesure': 'measurement',
        'force': 'force',
        'vitesse': 'speed',
        'masse': 'mass',
        'poids': 'weight',
        'température': 'temperature',
        'pression': 'pressure',
        'volume': 'volume',
        'densité': 'density',
        'chimique': 'chemical',
        'physique': 'physical',
        'biologie': 'biology',
        'organe': 'organ',
        'corps': 'body',
        'humain': 'human',
        'virus': 'virus',
        'bactérie': 'bacteria',
        'maladie': 'disease',
        'santé': 'health',
        'os': 'bone',
        'sang': 'blood',
        'cœur': 'heart',
        'cerveau': 'brain',
        'poumon': 'lung',
        'foie': 'liver',
        'rein': 'kidney',
        'estomac': 'stomach',
        'intestin': 'intestine',
        'muscle': 'muscle',
        'nerf': 'nerve',
        'artère': 'artery',
        'veine': 'vein',
        'structure': 'structure',
        'découvrir': 'discover',
        'découvert': 'discovered',
        'symbole': 'symbol',
        'adulte': 'adult',
        'enfant': 'child',
        'cause': 'cause',
        'causer': 'cause',
        'provoque': 'cause',
        'provoquer': 'cause',
        'grand': 'large',
        'grande': 'large',
        'petit': 'small',
        'petite': 'small',
        'plus': 'most',
        'moins': 'least',
      },
      'ar': {
        'planète': 'كوكب',
        'étoile': 'نجم',
        'soleil': 'شمس',
        'lune': 'قمر',
        'terre': 'أرض',
        'eau': 'ماء',
        'air': 'هواء',
        'feu': 'نار',
        'lumière': 'ضوء',
        'chaleur': 'حرارة',
        'énergie': 'طاقة',
        'unité': 'وحدة',
        'mesure': 'قياس',
        'force': 'قوة',
        'vitesse': 'سرعة',
        'masse': 'كتلة',
        'poids': 'وزن',
        'température': 'درجة الحرارة',
        'pression': 'ضغط',
        'volume': 'حجم',
        'densité': 'كثافة',
        'chimique': 'كيميائي',
        'physique': 'فيزيائي',
        'biologie': 'علم الأحياء',
        'organe': 'عضو',
        'corps': 'جسم',
        'humain': 'إنسان',
        'virus': 'فيروس',
        'bactérie': 'بكتيريا',
        'maladie': 'مرض',
        'santé': 'صحة',
        'os': 'عظم',
        'sang': 'دم',
        'cœur': 'قلب',
        'cerveau': 'دماغ',
        'poumon': 'رئة',
        'foie': 'كبد',
        'rein': 'كلية',
        'estomac': 'معدة',
        'intestin': 'أمعاء',
        'muscle': 'عضلة',
        'nerf': 'عصب',
        'artère': 'شريان',
        'veine': 'وريد',
        'structure': 'بنية',
        'découvrir': 'اكتشف',
        'découvert': 'مكتشف',
        'symbole': 'رمز',
        'adulte': 'بالغ',
        'enfant': 'طفل',
        'cause': 'سبب',
        'causer': 'يسبب',
        'provoque': 'يسبب',
        'provoquer': 'يسبب',
        'grand': 'كبير',
        'grande': 'كبيرة',
        'petit': 'صغير',
        'petite': 'صغيرة',
        'plus': 'أكثر',
        'moins': 'أقل',
      },
      'zh': {
        'planète': '行星',
        'étoile': '星',
        'soleil': '太阳',
        'lune': '月亮',
        'terre': '地球',
        'eau': '水',
        'air': '空气',
        'feu': '火',
        'lumière': '光',
        'chaleur': '热',
        'énergie': '能量',
        'unité': '单位',
        'mesure': '测量',
        'force': '力',
        'vitesse': '速度',
        'masse': '质量',
        'poids': '重量',
        'température': '温度',
        'pression': '压力',
        'volume': '体积',
        'densité': '密度',
        'chimique': '化学',
        'physique': '物理',
        'biologie': '生物学',
        'organe': '器官',
        'corps': '身体',
        'humain': '人类',
        'virus': '病毒',
        'bactérie': '细菌',
        'maladie': '疾病',
        'santé': '健康',
        'os': '骨',
        'sang': '血',
        'cœur': '心脏',
        'cerveau': '大脑',
        'poumon': '肺',
        'foie': '肝',
        'rein': '肾',
        'estomac': '胃',
        'intestin': '肠',
        'muscle': '肌肉',
        'nerf': '神经',
        'artère': '动脉',
        'veine': '静脉',
        'structure': '结构',
        'découvrir': '发现',
        'découvert': '发现的',
        'symbole': '符号',
        'adulte': '成人',
        'enfant': '儿童',
        'cause': '原因',
        'causer': '导致',
        'provoque': '引起',
        'provoquer': '引发',
        'grand': '大',
        'grande': '大',
        'petit': '小',
        'petite': '小',
        'plus': '最',
        'moins': '最少',
      },
      'hi': {
        'planète': 'ग्रह',
        'étoile': 'तारा',
        'soleil': 'सूर्य',
        'lune': 'चंद्रमा',
        'terre': 'पृथ्वी',
        'eau': 'पानी',
        'air': 'हवा',
        'feu': 'आग',
        'lumière': 'प्रकाश',
        'chaleur': 'गर्मी',
        'énergie': 'ऊर्जा',
        'unité': 'इकाई',
        'mesure': 'माप',
        'force': 'बल',
        'vitesse': 'गति',
        'masse': 'द्रव्यमान',
        'poids': 'वजन',
        'température': 'तापमान',
        'pression': 'दबाव',
        'volume': 'आयतन',
        'densité': 'घनत्व',
        'chimique': 'रासायनिक',
        'physique': 'भौतिक',
        'biologie': 'जीव विज्ञान',
        'organe': 'अंग',
        'corps': 'शरीर',
        'humain': 'मानव',
        'virus': 'वायरस',
        'bactérie': 'जीवाणु',
        'maladie': 'बीमारी',
        'santé': 'स्वास्थ्य',
        'os': 'हड्डी',
        'sang': 'रक्त',
        'cœur': 'हृदय',
        'cerveau': 'मस्तिष्क',
        'poumon': 'फेफड़ा',
        'foie': 'यकृत',
        'rein': 'गुर्दा',
        'estomac': 'पेट',
        'intestin': 'आंत',
        'muscle': 'मांसपेशी',
        'nerf': 'तंत्रिका',
        'artère': 'धमनी',
        'veine': 'शिरा',
        'structure': 'संरचना',
        'découvrir': 'खोजना',
        'découvert': 'खोजा',
        'symbole': 'प्रतीक',
        'adulte': 'वयस्क',
        'enfant': 'बच्चा',
        'cause': 'कारण',
        'causer': 'कारण बनता है',
        'provoque': 'कारण बनता है',
        'provoquer': 'कारण बनाना',
        'grand': 'बड़ा',
        'grande': 'बड़ी',
        'petit': 'छोटा',
        'petite': 'छोटी',
        'plus': 'सबसे',
        'moins': 'कम से कम',
      },
      'es': {
        'planète': 'planeta',
        'étoile': 'estrella',
        'soleil': 'sol',
        'lune': 'luna',
        'terre': 'tierra',
        'eau': 'agua',
        'air': 'aire',
        'feu': 'fuego',
        'lumière': 'luz',
        'chaleur': 'calor',
        'énergie': 'energía',
        'unité': 'unidad',
        'mesure': 'medida',
        'force': 'fuerza',
        'vitesse': 'velocidad',
        'masse': 'masa',
        'poids': 'peso',
        'température': 'temperatura',
        'pression': 'presión',
        'volume': 'volumen',
        'densité': 'densidad',
        'chimique': 'químico',
        'physique': 'físico',
        'biologie': 'biología',
        'organe': 'órgano',
        'corps': 'cuerpo',
        'humain': 'humano',
        'virus': 'virus',
        'bactérie': 'bacteria',
        'maladie': 'enfermedad',
        'santé': 'salud',
        'os': 'hueso',
        'sang': 'sangre',
        'cœur': 'corazón',
        'cerveau': 'cerebro',
        'poumon': 'pulmón',
        'foie': 'hígado',
        'rein': 'riñón',
        'estomac': 'estómago',
        'intestin': 'intestino',
        'muscle': 'músculo',
        'nerf': 'nervio',
        'artère': 'arteria',
        'veine': 'vena',
        'structure': 'estructura',
        'découvrir': 'descubrir',
        'découvert': 'descubierto',
        'symbole': 'símbolo',
        'adulte': 'adulto',
        'enfant': 'niño',
        'cause': 'causa',
        'causer': 'causar',
        'provoque': 'provoca',
        'provoquer': 'provocar',
        'grand': 'grande',
        'grande': 'grande',
        'petit': 'pequeño',
        'petite': 'pequeña',
        'plus': 'más',
        'moins': 'menos',
      },
    },
    'math': {
      'en': {
        'nombre': 'number',
        'chiffre': 'digit',
        'plus': 'plus',
        'moins': 'minus',
        'fois': 'times',
        'divisé': 'divided',
        'égal': 'equal',
        'résultat': 'result',
        'somme': 'sum',
        'différence': 'difference',
        'produit': 'product',
        'cube': 'cube',
        'carré': 'square',
        'racine': 'root',
        'puissance': 'power',
        'pourcentage': 'percentage',
        'fraction': 'fraction',
        'décimal': 'decimal',
        'entier': 'integer',
        'pair': 'even',
        'impair': 'odd',
        'multiple': 'multiple',
        'diviseur': 'divisor',
        'quotient': 'quotient',
        'reste': 'remainder',
        'périmètre': 'perimeter',
        'aire': 'area',
        'surface': 'surface',
        'volume': 'volume',
        'angle': 'angle',
        'triangle': 'triangle',
        'cercle': 'circle',
        'rectangle': 'rectangle',
      },
      'ar': {
        'nombre': 'عدد',
        'plus': 'زائد',
        'moins': 'ناقص',
        'fois': 'مرات',
        'égal': 'يساوي',
        'résultat': 'نتيجة',
        'somme': 'مجموع',
        'cube': 'مكعب',
        'carré': 'مربع',
        'racine': 'جذر',
        'puissance': 'قوة',
        'pourcentage': 'نسبة مئوية',
        'fraction': 'كسر',
        'décimal': 'عشري',
        'entier': 'عدد صحيح',
        'pair': 'زوجي',
        'impair': 'فردي',
        'multiple': 'مضاعف',
        'diviseur': 'قاسم',
        'quotient': 'حاصل القسمة',
        'reste': 'باقي',
        'périmètre': 'محيط',
        'aire': 'مساحة',
        'surface': 'سطح',
        'volume': 'حجم',
        'angle': 'زاوية',
        'triangle': 'مثلث',
        'cercle': 'دائرة',
        'rectangle': 'مستطيل',
      },
      'zh': {
        'nombre': '数',
        'plus': '加',
        'moins': '减',
        'fois': '乘',
        'égal': '等于',
        'résultat': '结果',
        'somme': '和',
        'cube': '立方',
        'carré': '平方',
        'racine': '根',
        'puissance': '幂',
        'pourcentage': '百分比',
        'fraction': '分数',
        'décimal': '小数',
        'entier': '整数',
        'pair': '偶数',
        'impair': '奇数',
        'multiple': '倍数',
        'diviseur': '除数',
        'quotient': '商',
        'reste': '余数',
        'périmètre': '周长',
        'aire': '面积',
        'surface': '表面',
        'volume': '体积',
        'angle': '角',
        'triangle': '三角形',
        'cercle': '圆',
        'rectangle': '矩形',
      },
      'hi': {
        'nombre': 'संख्या',
        'plus': 'जोड़',
        'moins': 'घटा',
        'fois': 'गुणा',
        'égal': 'बराबर',
        'résultat': 'परिणाम',
        'somme': 'योग',
        'cube': 'घन',
        'carré': 'वर्ग',
        'racine': 'वर्गमूल',
        'puissance': 'घात',
        'pourcentage': 'प्रतिशत',
        'fraction': 'भिन्न',
        'décimal': 'दशमलव',
        'entier': 'पूर्णांक',
        'pair': 'सम',
        'impair': 'विषम',
        'multiple': 'गुणज',
        'diviseur': 'भाजक',
        'quotient': 'भागफल',
        'reste': 'शेषफल',
        'périmètre': 'परिमाप',
        'aire': 'क्षेत्रफल',
        'surface': 'सतह',
        'volume': 'आयतन',
        'angle': 'कोण',
        'triangle': 'त्रिभुज',
        'cercle': 'वृत्त',
        'rectangle': 'आयत',
      },
      'es': {
        'nombre': 'número',
        'plus': 'más',
        'moins': 'menos',
        'fois': 'veces',
        'égal': 'igual',
        'résultat': 'resultado',
        'somme': 'suma',
        'cube': 'cubo',
        'carré': 'cuadrado',
        'racine': 'raíz',
        'puissance': 'potencia',
        'pourcentage': 'porcentaje',
        'fraction': 'fracción',
        'décimal': 'decimal',
        'entier': 'entero',
        'pair': 'par',
        'impair': 'impar',
        'multiple': 'múltiplo',
        'diviseur': 'divisor',
        'quotient': 'cociente',
        'reste': 'resto',
        'périmètre': 'perímetro',
        'aire': 'área',
        'surface': 'superficie',
        'volume': 'volumen',
        'angle': 'ángulo',
        'triangle': 'triángulo',
        'cercle': 'círculo',
        'rectangle': 'rectángulo',
      },
    },
    'sports': {
      'en': {
        'football': 'football',
        'joueur': 'player',
        'équipe': 'team',
        'match': 'match',
        'coupe': 'cup',
        'champion': 'champion',
        'but': 'goal',
        'ballon': 'ball',
        'stade': 'stadium',
      },
      'ar': {
        'football': 'كرة القدم',
        'joueur': 'لاعب',
        'équipe': 'فريق',
        'match': 'مباراة',
        'coupe': 'كأس',
        'champion': 'بطل',
        'but': 'هدف',
        'ballon': 'كرة',
        'stade': 'ملعب',
      },
      'zh': {
        'football': '足球',
        'joueur': '球员',
        'équipe': '队',
        'match': '比赛',
        'coupe': '杯',
        'champion': '冠军',
        'but': '进球',
        'ballon': '球',
        'stade': '体育场',
      },
      'hi': {
        'football': 'फुटबॉल',
        'joueur': 'खिलाड़ी',
        'équipe': 'टीम',
        'match': 'मैच',
        'coupe': 'कप',
        'champion': 'चैंपियन',
        'but': 'गोल',
        'ballon': 'गेंद',
        'stade': 'स्टेडियम',
      },
      'es': {
        'football': 'fútbol',
        'joueur': 'jugador',
        'équipe': 'equipo',
        'match': 'partido',
        'coupe': 'copa',
        'champion': 'campeón',
        'but': 'gol',
        'ballon': 'balón',
        'stade': 'estadio',
      },
    },
    'music': {
      'en': {
        'musique': 'music',
        'chanson': 'song',
        'instrument': 'instrument',
        'artiste': 'artist',
        'album': 'album',
        'concert': 'concert',
        'guitare': 'guitar',
        'piano': 'piano',
        'batterie': 'drums',
      },
      'ar': {
        'musique': 'موسيقى',
        'chanson': 'أغنية',
        'instrument': 'آلة موسيقية',
        'artiste': 'فنان',
        'album': 'ألبوم',
        'concert': 'حفل',
      },
      'zh': {
        'musique': '音乐',
        'chanson': '歌曲',
        'instrument': '乐器',
        'artiste': '艺术家',
        'album': '专辑',
        'concert': '音乐会',
      },
      'hi': {
        'musique': 'संगीत',
        'chanson': 'गाना',
        'instrument': 'वाद्य यंत्र',
        'artiste': 'कलाकार',
        'album': 'एल्बम',
        'concert': 'संगीत कार्यक्रम',
      },
      'es': {
        'musique': 'música',
        'chanson': 'canción',
        'instrument': 'instrumento',
        'artiste': 'artista',
        'album': 'álbum',
        'concert': 'concierto',
      },
    },
  };

  /// Patterns de questions
  static final Map<String, Map<String, String>> _questionPatterns = {
    'en': {
      'Quel est le': 'What is the',
      'Quel est la': 'What is the',
      'Quelle est le': 'What is the',
      'Quelle est la': 'What is the',
      'Quel était le': 'What was the',
      'Quel était la': 'What was the',
      'Quelle était le': 'What was the',
      'Quelle était la': 'What was the',
      'Qui est': 'Who is',
      'Qui était': 'Who was',
      'En quelle année': 'In what year',
      'Combien': 'How many',
      'Comment': 'How',
      'Pourquoi': 'Why',
      'Où': 'Where',
      'Quand': 'When',
      'Quel': 'What',
      'Quelle': 'What',
      'Quels': 'What',
      'Quelles': 'What',
    },
    'ar': {
      'Quel est le': 'ما هو ال',
      'Quel est la': 'ما هي ال',
      'Quel est': 'ما هو',
      'Quelle est le': 'ما هو ال',
      'Quelle est la': 'ما هي ال',
      'Quelle est': 'ما هي',
      'Quels sont les': 'ما هي ال',
      'Quels sont': 'ما هي',
      'Quelles sont les': 'ما هي ال',
      'Quelles sont': 'ما هي',
      'Qui est le': 'من هو ال',
      'Qui est la': 'من هي ال',
      'Qui est': 'من هو',
      'Qui était le': 'من كان ال',
      'Qui était la': 'من كانت ال',
      'Qui était': 'من كان',
      'Qui sont les': 'من هم ال',
      'Qui sont': 'من هم',
      'Qui étaient les': 'من كانوا ال',
      'Qui étaient': 'من كانوا',
      'Que signifie': 'ماذا يعني',
      'Que veut dire': 'ماذا يعني',
      'Que représente': 'ماذا يمثل',
      'Que désigne': 'ماذا يشير',
      'Combien de': 'كم عدد',
      'Combien': 'كم',
      'Comment appelle-t-on': 'ماذا نسمي',
      'Comment appelle': 'كيف نسمي',
      'Comment se nomme': 'ما اسم',
      'Comment': 'كيف',
      'Pourquoi': 'لماذا',
      'Où se trouve': 'أين يقع',
      'Où est situé': 'أين يقع',
      'Où est située': 'أين تقع',
      'Où est': 'أين',
      'Où': 'أين',
      'Quand a eu lieu': 'متى حدث',
      'Quand est né': 'متى ولد',
      'Quand est morte': 'متى ماتت',
      'Quand': 'متى',
      'À quelle date': 'في أي تاريخ',
      'En quelle année': 'في أي عام',
      'En quel siècle': 'في أي قرن',
      'De quelle couleur': 'ما لون',
      'De quel pays': 'من أي بلد',
      'De quelle nationalité': 'ما جنسية',
      'Dans quel pays': 'في أي بلد',
      'Dans quelle ville': 'في أي مدينة',
      'Dans quelle région': 'في أي منطقة',
      'Lequel de ces': 'أي من هذه',
      'Laquelle de ces': 'أي من هذه',
      'Parmi ces': 'من بين هذه',
      'Selon': 'حسب',
    },
    'zh': {
      'Quel est': '什么是',
      'Quelle est': '什么是',
      'Qui est': '谁是',
      'En quelle année': '在哪一年',
      'Combien': '多少',
      'Comment': '怎么',
      'Pourquoi': '为什么',
      'Où': '在哪里',
      'Quand': '什么时候',
    },
    'hi': {
      'Quel est': 'क्या है',
      'Quelle est': 'क्या है',
      'Qui est': 'कौन है',
      'Qui était': 'कौन था',
      'En quelle année': 'किस वर्ष में',
      'Combien': 'कितने',
      'Comment': 'कैसे',
      'Pourquoi': 'क्यों',
      'Où': 'कहाँ',
      'Quand': 'कब',
    },
    'es': {
      'Quel est': 'Cuál es',
      'Quelle est': 'Cuál es',
      'Qui est': 'Quién es',
      'Qui était': 'Quién era',
      'En quelle année': 'En qué año',
      'Combien': 'Cuántos',
      'Comment': 'Cómo',
      'Pourquoi': 'Por qué',
      'Où': 'Dónde',
      'Quand': 'Cuándo',
    },
  };

  /// Traduit automatiquement une question
  static String translateQuestion(String question, String targetLang,
      {String? category}) {
    if (targetLang == 'fr') return question;

    String translated = question;

    // 1. Appliquer les patterns de questions (TRIÉ DU PLUS LONG AU PLUS COURT)
    final patterns = _questionPatterns[targetLang] ?? {};
    final sortedEntries = patterns.entries.toList()
      ..sort((a, b) => b.key.length.compareTo(a.key.length)); // ✅ Décroissant

    for (var entry in sortedEntries) {
      if (translated.startsWith(entry.key)) {
        translated = translated.replaceFirst(entry.key, entry.value);
        break;
      }
    }

    // 2. ✅ NOUVEAU : Gérer les contractions françaises AVANT word boundaries
    // Ordre important : expressions longues d'abord !
    translated = _replaceContractions(translated, targetLang);

    // 3. Déterminer le domaine et appliquer les termes
    final domains = _detectDomains(question, category);
    // ✅ AMÉLIORATION : caseSensitive = true pour arabe (diacritiques importantes)
    final useCaseSensitive = (targetLang == 'ar' || targetLang == 'he');

    for (var domain in domains) {
      final terms = _domainTerms[domain]?[targetLang] ?? {};
      for (var entry in terms.entries) {
        // Remplacement avec sensibilité à la casse adaptée
        translated = translated.replaceAll(
            RegExp('\\b${RegExp.escape(entry.key)}\\b',
                caseSensitive: useCaseSensitive), // ✅ true pour AR/HE
            entry.value);
        // Ajouter remplacement sans boundary pour cas apostrophe
        translated = translated.replaceAll(
            RegExp("${RegExp.escape(entry.key)}'",
                caseSensitive: useCaseSensitive),
            "${entry.value}'");
      }
    }

    return translated;
  }

  /// Remplace les contractions françaises (l', d', etc.)
  static String _replaceContractions(String text, String targetLang) {
    final contractions = {
      'en': {
        "l'empire": "the empire",
        "l'organe": "the organ",
        "l'unité": "the unit",
        "l'année": "the year",
        "l'histoire": "the history",
        "l'indépendance": "the independence",
        "d'histoire": "of history",
        "d'indépendance": "of independence",
      },
      'ar': {
        // Articles définis l'...
        "l'empire": "الإمبراطورية",
        "l'organe": "العضو",
        "l'unité": "الوحدة",
        "l'année": "العام",
        "l'histoire": "التاريخ",
        "l'indépendance": "الاستقلال",
        "l'homme": "الرجل",
        "l'eau": "الماء",
        "l'air": "الهواء",
        "l'art": "الفن",
        "l'or": "الذهب",
        "l'État": "الدولة",
        "l'Afrique": "أفريقيا",
        "l'Europe": "أوروبا",
        "l'Asie": "آسيا",
        "l'Amérique": "أمريكا",
        "l'univers": "الكون",
        "l'océan": "المحيط",
        "l'animal": "الحيوان",
        "l'armée": "الجيش",
        "l'énergie": "الطاقة",
        "l'espace": "الفضاء",
        "l'île": "الجزيرة",
        "l'étoile": "النجمة",
        "l'atome": "الذرة",
        // Prépositions d'...
        "d'histoire": "من التاريخ",
        "d'indépendance": "من الاستقلال",
        "d'un": "من",
        "d'une": "من",
        "d'autres": "من غيرها",
        "d'abord": "أولا",
        "d'eau": "من الماء",
        "d'air": "من الهواء",
        "d'Afrique": "من أفريقيا",
        "d'Europe": "من أوروبا",
        "d'Asie": "من آسيا",
        "d'Amérique": "من أمريكا",
        "d'or": "من الذهب",
        "d'argent": "من الفضة",
        // Conjonctions qu'...
        "qu'il": "أنه",
        "qu'elle": "أنها",
        "qu'on": "أن",
        "qu'un": "أن",
        "qu'une": "أن",
        "qu'ils": "أنهم",
        "qu'elles": "أنهن",
        "qu'est-ce": "ماذا",
        // Verbes s'...
        "s'appelle": "يسمى",
        "s'appelait": "كان يسمى",
        "s'est": "قد",
        "s'était": "كان",
        "s'agit": "يتعلق",
        // Autres contractions
        "c'est": "إنه",
        "c'était": "كان",
        "n'est": "ليس",
        "n'était": "لم يكن",
        "n'a": "ليس لديه",
        "n'ont": "ليس لديهم",
        "j'ai": "لدي",
        "j'étais": "كنت",
        "m'appelle": "اسمي",
        "t'appelle": "اسمك",
      },
      'zh': {
        "l'empire": "帝国",
        "l'organe": "器官",
        "l'unité": "单位",
        "l'année": "年",
        "l'histoire": "历史",
        "l'indépendance": "独立",
        "d'histoire": "历史的",
        "d'indépendance": "独立的",
      },
      'hi': {
        "l'empire": "साम्राज्य",
        "l'organe": "अंग",
        "l'unité": "इकाई",
        "l'année": "वर्ष",
        "l'histoire": "इतिहास",
        "l'indépendance": "स्वतंत्रता",
        "d'histoire": "इतिहास का",
        "d'indépendance": "स्वतंत्रता का",
        "d'années": "वर्ष",
        "de km": "किमी",
        "millions de": "मिलियन",
        "milliards d'": "बिलियन",
      },
      'es': {
        "l'empire": "el imperio",
        "l'organe": "el órgano",
        "l'unité": "la unidad",
        "l'année": "el año",
        "l'histoire": "la historia",
        "l'indépendance": "la independencia",
        "d'histoire": "de historia",
        "d'indépendance": "de independencia",
      },
    };

    final langContractions = contractions[targetLang] ?? {};
    String result = text;

    // Remplacer en ordre décroissant de longueur pour éviter conflits
    final sortedEntries = langContractions.entries.toList()
      ..sort((a, b) => b.key.length.compareTo(a.key.length));

    for (var entry in sortedEntries) {
      result = result.replaceAll(
          RegExp(RegExp.escape(entry.key), caseSensitive: false), entry.value);
    }

    return result;
  }

  /// Détecte les domaines dans une question
  static List<String> _detectDomains(String question, String? category) {
    // ✅ TOUJOURS inclure "common" pour les mots fréquents (de, le, la, etc.)
    final domains = <String>['common'];
    final lowerQuestion = question.toLowerCase();
    final lowerCategory = category?.toLowerCase() ?? '';

    // ✅ AMÉLIORATION 1: Catégorie "Culture générale" inclut TOUS les domaines
    if (lowerCategory.contains('culture') &&
        lowerCategory.contains('général')) {
      domains.addAll(
          ['history', 'geography', 'science', 'math', 'sports', 'music']);
      return domains; // Retour anticipé avec tous les domaines
    }

    // Détection par catégorie (méthode existante)
    if (lowerCategory.contains('histoire') ||
        lowerCategory.contains('history')) {
      domains.add('history');
    }
    if (lowerCategory.contains('géographie') ||
        lowerCategory.contains('afrique')) {
      domains.add('geography');
    }
    if (lowerCategory.contains('science') ||
        lowerCategory.contains('santé') ||
        lowerCategory.contains('health')) {
      domains.add('science');
    }
    if (lowerCategory.contains('math')) {
      domains.add('math');
    }
    if (lowerCategory.contains('football') || lowerCategory.contains('sport')) {
      domains.add('sports');
    }
    if (lowerCategory.contains('musique') || lowerCategory.contains('music')) {
      domains.add('music');
    }

    // ✅ AMÉLIORATION 2: Détection par mots-clés dans le CONTENU de la question
    // Historique
    if (lowerQuestion.contains(RegExp(
        r'\b(roi|reine|empereur|empire|guerre|bataille|révolution|président|indépendance|siècle|dynastie)\b'))) {
      if (!domains.contains('history')) domains.add('history');
    }

    // Géographique
    if (lowerQuestion.contains(RegExp(
        r'\b(pays|ville|capitale|région|continent|fleuve|montagne|océan|mer|désert)\b'))) {
      if (!domains.contains('geography')) domains.add('geography');
    }

    // Scientifique
    if (lowerQuestion.contains(RegExp(
        r'\b(planète|étoile|cellule|organe|atome|molécule|énergie|vitesse|température)\b'))) {
      if (!domains.contains('science')) domains.add('science');
    }

    // Mathématique
    if (lowerQuestion.contains(RegExp(
        r'\b(nombre|carré|racine|somme|puissance|triangle|cercle|angle)\b'))) {
      if (!domains.contains('math')) domains.add('math');
    }

    // Détection par mots-clés dans la question (ancien code)
    if (lowerQuestion.contains('pays') ||
        lowerQuestion.contains('capitale') ||
        lowerQuestion.contains('ville')) {
      if (!domains.contains('geography')) domains.add('geography');
    }
    if (lowerQuestion.contains('empire') ||
        lowerQuestion.contains('guerre') ||
        lowerQuestion.contains('roi')) {
      if (!domains.contains('history')) domains.add('history');
    }
    if (lowerQuestion.contains('planète') ||
        lowerQuestion.contains('atome') ||
        lowerQuestion.contains('énergie') ||
        lowerQuestion.contains('virus') ||
        lowerQuestion.contains('organe')) {
      if (!domains.contains('science')) domains.add('science');
    }
    if (lowerQuestion.contains('cube') ||
        lowerQuestion.contains('carré') ||
        lowerQuestion.contains('nombre')) {
      if (!domains.contains('math')) domains.add('math');
    }

    return domains;
  }

  /// Traduit une liste de réponses
  static List<String> translateAnswers(List<String> answers, String targetLang,
      {String? category}) {
    return answers
        .map((answer) =>
            translateQuestion(answer, targetLang, category: category))
        .toList();
  }
}
